import React, { useEffect, useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { generatePlan } from '../api/client.js'
import RoadmapCard from '../components/RoadmapCard.jsx'

const LOADING_MESSAGES = [
  'Reading your profile…',
  'Analyzing community experiences…',
  'Identifying your differentiation opportunities…',
  'Building your personalized roadmap with Amazon Bedrock…',
]

export default function Roadmap() {
  const navigate = useNavigate()
  const [roadmap, setRoadmap] = useState(null)
  const [userProfile, setUserProfile] = useState(null)
  const [loading, setLoading] = useState(true)
  const [loadingMsg, setLoadingMsg] = useState(0)
  const [error, setError] = useState(null)

  useEffect(() => {
    const stored = sessionStorage.getItem('pathmentor_user_context')
    if (!stored) {
      navigate('/start')
      return
    }

    const ctx = JSON.parse(stored)
    setUserProfile(ctx)

    // Cycle through loading messages to keep user engaged
    const msgInterval = setInterval(() => {
      setLoadingMsg(m => (m + 1) % LOADING_MESSAGES.length)
    }, 2000)

    generatePlan(ctx)
      .then(data => {
        setRoadmap(data.roadmap)
      })
      .catch(err => setError(err.message))
      .finally(() => {
        setLoading(false)
        clearInterval(msgInterval)
      })

    return () => clearInterval(msgInterval)
  }, [navigate])

  if (loading) {
    return (
      <div className="loading-center" style={{ minHeight: '80vh' }}>
        <div style={{
          width: 64, height: 64,
          background: 'linear-gradient(135deg, #6C3AFF, #FF6B35)',
          borderRadius: '50%',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: '1.8rem',
          animation: 'pulse-glow 2s infinite',
        }}>
          🤖
        </div>
        <h3 style={{ color: 'var(--text-primary)', marginTop: 8 }}>Generating Your Roadmap</h3>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', transition: 'all 0.3s' }}>
          {LOADING_MESSAGES[loadingMsg]}
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginTop: 8 }}>
          This usually takes 10–20 seconds
        </p>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container-sm" style={{ paddingTop: 60 }}>
        <div className="error-banner">
          Failed to generate roadmap: {error}
          <br />
          <span style={{ fontSize: '0.85rem', opacity: 0.8 }}>
            Make sure Amazon Bedrock model access is enabled in your AWS account.
          </span>
        </div>
        <div style={{ display: 'flex', gap: 12, marginTop: 16 }}>
          <button className="btn btn-primary" onClick={() => window.location.reload()}>Try Again</button>
          <button className="btn btn-secondary" onClick={() => navigate('/insights')}>← View Insights Instead</button>
        </div>
      </div>
    )
  }

  return (
    <div style={{ padding: '60px 0 80px' }}>
      <div className="container-sm">

        {/* Header */}
        <div style={{ marginBottom: 40 }}>
          <Link to="/insights" style={{ fontSize: '0.85rem', color: 'var(--text-muted)', display: 'inline-flex', alignItems: 'center', gap: 6, marginBottom: 24 }}>
            ← Back to Insights
          </Link>
          <h1 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.25rem)', marginBottom: 12 }}>
            Your <span className="gradient-text">Personalized Roadmap</span>
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>
            Generated by Amazon Bedrock using real community experiences and your profile.
          </p>
        </div>

        <RoadmapCard roadmap={roadmap} userProfile={userProfile} />

        {/* Footer Actions */}
        <div style={{ marginTop: 48, display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center' }}>
          <button className="btn btn-primary" onClick={() => window.location.reload()}>
            🔄 Regenerate Plan
          </button>
          <Link to="/experiences" className="btn btn-secondary">
            Browse More Experiences
          </Link>
          <Link to="/start" className="btn btn-ghost">
            Start Over
          </Link>
        </div>

      </div>
    </div>
  )
}